Add fragment arguments RFC to agenda
graphql/graphql-wg pull request #1526
Opened 2024-06-04 11:27 UTC by JoviDeCroock

2024-06-04 11:28 UTC, JoviDeCroock commented on agendas/2024/06-Jun/06-wg-primary.md
>  1. Open pull requests (1m, Jovi)
```suggestion
1. Open pull requests (5m, Jovi)
```

2024-06-05 10:12 UTC, benjie requested changes
Splitting this into two separate agenda items, and allocating more time to fragment arguments.

2024-06-05 10:12 UTC, benjie commented on agendas/2024/06-Jun/06-wg-primary.md
> +   - Moving the Fragment arguments RFC to [RFC2](https://github.com/graphql/graphql-spec/pull/1081#issuecomment-2147284040)
```suggestion
1. Editorial change to "composite" term (2m, Jovi)
   - [PR; two approvals](https://github.com/graphql/graphql-spec/pull/1078)
1. Move Fragment Arguments RFC to RFC2? (10m, Jovi)
   - [RFC](https://github.com/graphql/graphql-spec/pull/1081#issuecomment-2147284040)
```

2024-06-05 10:12 UTC, benjie approved these changes

2024-06-05 10:13 UTC, merged